Update Rust toolchain version to 1.90.0
Linux Musl build fails with error. Hence updating to latest stable 

```
error: failed to compile `cross v0.2.5 (https://github.com/cross-rs/cross#49cd054d)`, intermediate artifacts can be found at `/tmp/cargo-installQ6m96F`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
  rustc 1.87.0 is not supported by the following package:
    home@0.5.12 requires rustc 1.88
```